pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('jenkins-aws-secret-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('jenkins-aws-secret-access-key')
    }

    parameters{
        string(name: 'yourGrettings', defaultValue: 'Hi', description: 'Your grettings phrase')
        choice(name: 'yourChoice', choices: ["one", "two", 3], description: 'Pick something')
    }

    stages {
        stage('Example') {
            steps {
                echo "${params.yourGrettings} Mr World Wide"
                echo "This are my choices: ${params.youChoice}"
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                echo 'AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}'
                echo 'AWS_ACCESS_KEY_ID: ${AWS_SECRET_ACCESS_KEY}'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    
    post{
        success {
            mail(to: 'mart.cervants@gmail.com', subject: 'The Pipeline succed :(', body: 'The Pipeline succed.')
        }
    }
}